travis:
  secure:
    BINSTAR_TOKEN: O/qgWNpD9U0xt4uFdyRcUs2egseTbQTGmVhE5Uyjr3z3hhLMDxY45i4uQ88RpHfaQRhxth0S8AzeU88v0E9gWz4G44/POIVH0MrgYU9yUQdmw/Dfotnn8mVExiUr3neUWV9Hmm3GvhYoW3KonrdK14jQs3l6w9e9WmcYQpYASghmuWCsKY65kPu6jVgxtMyksbafP6PqhjAAkd7xByZiWvOULMMcevhm9T+DkOjD7F0ipTcxv0xgopKiQfwBZCEm3WWdFX3zxzXH1SG4BkTOgiaa8DV9yHKWt97iFSFVHaMzKQM1+kl+FI+JgwfOTdo6ZSvkxn/nTsO7Z2XRpA633iPe1w2pkQAMl+wd4UuRwsb5PtSC0j8/kcqS2pLJH4LPKbBxnU6FY/kCO91yJtkQtOg/pLtOE03iE7VI5FpslNE5iI2h3GBKjyk0akJ6zU2UyJ/cEA43NVE0Vnf0mefkHwen85PSWp8Qq/3Y2gDIdMuKUgXK1bKOy3UdrpV1MKX8I1vRARscAGjjIJhFq8IYseUFqz9V73GABgW0RCRqUeBwyjnBRABtbaXu0xrIm8J1ZY8IhucW8Mkjo3sIgc8ak0sEVeVOY7giV2ecn7FVYFaEMSEsqeheY9PXcn88aPEAYQcdYcb85b5pcvY+jy65Vzyx7ZDKzpDZBmN6FQRbpSw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
